all:
	gcc criacao_arquivos.c -o criacao_arquivos
	gcc leitura_arquivos.c -o leitura_arquivos
	gcc exclusao_arquivos.c -o exclusao_arquivos

run:
	./criacao_arquivos
	./leitura_arquivos
	./exclusao_arquivos
